#!/usr/bin/env bash

set -e

test_logs=".build/logs"
[[ -d "$test_logs" ]] || mkdir -p "$test_logs"
test_passing="$test_logs/passing"
test_failing="$test_logs/failing"

run_test() {
    local test="$1" ; shift
    case "$test" in
        test1) return 0 ;;
        test2) return 0 ;;
        test3) return 3 ;;
        test4) return 0 ;;
        test5) return 2 ;;
        test6) return 0 ;;
    esac
}

run_test_profile() {
    local test="$1" ; shift
    local exit_status='0'
    echo "running test '$test'" >&2
    run_test "$test" "$@" || exit_status="$?"
    echo "finished test '$test'" >&2
    if [[ "$exit_status" == '0' ]]; then
        echo "$test" >> "$test_passing"
    else
        echo "$test" >> "$test_failing"
    fi
    exit "$exit_status"
}

run_test_profile "$@"
